# Permalinks
highlighter: pygments
permalink:        pretty
relative_permalinks: true

# Setup
title:            Parkerrr
tagline:          'A Jekyll theme by Parkerrr'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              localhost
baseurl:          /

author:
  name:           'Jason Beaton'
  url:            https://twitter.com/thnkco

paginate:         10

